apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests

images:
  - name: ntt1902/shoesstore-backend
    newTag: latest

  - name: ntt1902/shoesstore-frontend
    newTag: latest