apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments/backend-config.yaml
  - deployments/backend.yaml
  - deployments/frontend.yaml
  - services/backend-service.yaml
  - services/frontend-service.yaml
  - ingresses/app-ingress.yaml